### ISSUE TITLE
Implement tota11y behind a dev flag

### ISSUE THREAD

**Issue by ghost** [hankchizljaw/stalfos#10]
Very useful for a11y work: http://khan.github.io/tota11y/

**Comment by Andy-set-studio** [comment]
Because tota11y can be added as a bookmarklet, I don't think it's worth adding to the framework. I'd hate to be responsible for accidental deployments with this in place. 

For those interested, you can add it as a bookmarklet by [following these steps](http://khan.github.io/tota11y/#Installation).

It is a really useful little tool though and has found itself deep in my workflow these days 👍
